version: 1.0.{build}
image: Visual Studio 2022

platform:
  - x64

build_script:
  - npm install
  - npm run build

artifacts:
  - path: dist\*.exe
    name: crypto-u-futures-calculator

deploy:
  provider: github
  auth_token: %GH_TOKEN%
  repo: your-username/crypto-u-calculator2.0
  on:
    branch: main
