version: 1.0.{build}

image: Visual Studio 2022

platform:
  - x64

build_script:
  - echo Building the Crypto-U Calculator...
  - python setup.py build  # 如果是 Python 应用程序
  - npm install && npm run build  # 如果是 Node.js 应用程序

artifacts:
  - path: bin\Release
    name: Crypto-U-Calculator

deploy:
  provider: GitHub
  auth_token:
    secure: <your-personal-access-token>
  release: Crypto-U Calculator v1.0
  description: "Crypto-U Calculator - 永续合约计算器"
  artifact: Crypto-U-Calculator
  draft: false
  prerelease: false
